name: Build and Lint

on:
  push:
    branches: beta
  pull_request:
  release: # Run when release is created
    types: [created]
    
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # the Node.js versions to build on
        node-version: [10.x, 12.x, 13.x, 14.x, 15.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }} 
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Lint the project
        run: npm run lint

      - name: Build the project
        run: npm run build
        env:
          CI: true

  publish-npm:
    # publish only if we are on our own repo, event was 'release' (a tag was created) and the tag starts with "v" (aka version tag)
    if: github.repository == 'home-connect/homebridge-zigbee2mqtt'

    needs: build # only run if build succeeds

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14 # use the minimum required version
          registry-url: https://registry.npmjs.org/
          scope: '@home-connect'
      - name: Install dependencies    
        run: npm install
      
      - run: node .github/workflows/prerelease.js
      
      - run: npm --no-git-tag-version version prerelease --preid=beta

      - name: Publish project        
      - run: npm publish --tag=beta
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}